### ISSUE TITLE
Resource 404s if no build is found

### ISSUE THREAD

**Issue by philwebb** [spring-io/artifactory-resource#14]
It should probably return empty JSON

**Comment by philwebb** [comment]
I'm not sure what I meant by this so closing for now.

**Comment by mbhave** [comment]
@philwebb I think I'm running into this now. Trying to upload an artifact to a test repo and I don't have an existing build. This is the error from the resource

```java
404 Not Found: [{
  "errors" : [ {
    "status" : 404,
    "message" : "No build was found for build name: mbhave-test-k8s-ci"
  } ]
}]
```
