### ISSUE TITLE
Not able to fetch artifact

### ISSUE THREAD

**Issue by vyomkumar** [spring-io/artifactory-resource#17]
I am not able to use a fetched artifact as a task input. My pipeline is very similar to the sample pipeline. The get step seems to run fine, yet the input directory inside the task container turns out empty. The resource check fails for some reason and states org.springframework.web.client.HttpClientErrorException: 404 Not Found. The example doesn't show using-a-fetched-artifact-as-a-task-input scenario, does it work?

**Comment by mbhave** [comment]
@vyomkumar Can you share a small project that replicates it?

**Comment by philwebb** [comment]
I assume this is no longer an issue. If it is, please provide a small sample that we can run.

**Comment by vyomkumar** [comment]
Sorry, I am not working on this anymore. Please feel free to close it.
