### ISSUE TITLE
Request Certificate Based Authentication

### ISSUE THREAD

**Issue by nsagoo-pivotal** [spring-io/artifactory-resource#54]
Requesting certificate-based authentication support for this resource type. 
https://www.jfrog.com/confluence/display/RTF/SSH+Integration

**Comment by mbhave** [comment]
We use Artifactory's REST API for fetching and deploying artifacts.My understanding is that it does not support certificate based authentication. See the [authentication section](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API) here. 

@nsagoo-pivotal We can re-open the issue if that is not the case and we can discuss further.
