### ISSUE TITLE
Support parallel upload and download of artifacts

### ISSUE THREAD

**Issue by philwebb** [spring-io/artifactory-resource#58]

**Comment by wilkinsona** [comment]
Parallel download seems to be fine, but parallel upload appears to cause corrupted of the `buildNumber`. For example, the following appeared in artifactory as a result of parallel deployment:

```
spring-boot-2.3.0.BUILD-20200110.154909-97-javadoc.jar   10-Jan-2020 15:49  1.57 MB
spring-boot-2.3.0.BUILD-20200110.154909-97-sources.jar   10-Jan-2020 15:49  756.98 KB
spring-boot-2.3.0.BUILD-20200110.154909-97.module        10-Jan-2020 15:49  4.57 KB
spring-boot-2.3.0.BUILD-20200110.154909-97.pom           10-Jan-2020 15:49  2.43 KB
spring-boot-2.3.0.BUILD-20200110.154909-98.jar           10-Jan-2020 15:49  999.60 KB
```

Note the four `-97`s and the one `-98`. Uploading in parallel changes to ordering of the artifacts as they're uploaded which regresses the fixes for #3 and #4. We need to be a bit smarter about how we split the work across threads.
