### ISSUE TITLE
Provide an option to download by searching in a specific repo

### ISSUE THREAD

**Issue by adarshasp87** [spring-io/artifactory-resource#60]
Provide an option to download artifact  by searching in a specific repository.

For Example
plan:
  - get: artifactory
      params: { repo: libs-release-local }

**Comment by mbhave** [comment]
@adarshasp87 Can you describe how you're using the resource a bit more? The `In/Get` step fetches artifacts using a build name and build number. Do the artifacts corresponding to the same build number have different repos in your case?

**Comment by philwebb** [comment]
I think we should stick to the build name and number. I'm going to close this one for now. If more details are provided then we can reopen it.
