### ISSUE TITLE
Retry deployment failures

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/artifactory-resource#71]
We sometimes see a deploy fail due to an Artifactory glitch. For example, [this Spring Boot build](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-2.3.x/jobs/build/builds/1453) failed due to a 404 with the following body:

```
 [{
  "errors" : [ {
    "status" : 404,
    "message" : "Unknown host - oss-sql-shared1"
  } ]
}]
```

These can leave the repository in a broken state with a partially deployed snapshot. It may be possible to retry the call that received the unexpected 404 response.

**Comment by snicoll** [comment]
We just had that when staging Spring Framework's `5.3.1`.

**Comment by wilkinsona** [comment]
The failure is sometimes a 400 too:

```
[{
  "errors" : [ {
    "status" : 400,
    "message" : "oss-sql-shared1: Name or service not known"
  } ]
}]
```
