### ISSUE TITLE
Register this resource type into the global list.

### ISSUE THREAD

**Issue by ringods** [spring-io/artifactory-resource#78]
This is purely a request from another Concourse user. Please make sure your resource type implementation can be found much easier: 

* register it so it can be found at https://resource-types.concourse-ci.org

Everything about registering can be found here:

https://github.com/concourse/resource-types#submitting-a-resource-type

**Comment by philwebb** [comment]
Thanks for the suggestion. I've opened https://github.com/concourse/resource-types/pull/65
