### ISSUE TITLE
Allow to download build by passing - build no

### ISSUE THREAD

**Issue by Ambarisha-006** [spring-io/artifactory-resource#88]
It would be great if we have option to download the cherry picked build, 
This will give option to deploy cherry picked build

```yaml
resources:
- name: artifacts
  type: artifactory-resource
  source:
    uri: https://repo.example.com
    username: admin
    password: secret
    build_name: my-build
    build_no: 11656400
```

@philwebb

**Comment by wilkinsona** [comment]
Pinning the resource to a specific build feels a bit odd to me. It would be analogous to pinning the git resource to a specific commit SHA or tag which it doesn't support. What's your use case for a resource that'll only ever download a specific build, @Ambarisha-006?

**Comment by Ambarisha-006** [comment]
> Pinning the resource to a specific build feels a bit odd to me. It would be analogous to pinning the git resource to a specific commit SHA or tag which it doesn't support. What's your use case for a resource that'll only ever download a specific build, @Ambarisha-006?

Scenario:
We have different environments, for each environments we will store the promoted artifacts version in git branch 
Now we want to download the specific build from jfrog and deploy
Ex:
Builds are in jfrog 
env a: build 1000
env b: build 1005
env c: build  999

**Comment by wilkinsona** [comment]
Sorry, I'm not sure I understand that. I think I understood that there's a version stored in a Git branch but I don't understand how that relates to the build number in the pipeline's configuration. Once the version's been updated in Git what will change the pipeline and update Concourse to use it?

**Comment by Ambarisha-006** [comment]
> Sorry, I'm not sure I understand that. I think I understood that there's a version stored in a Git branch but I don't understand how that relates to the build number in the pipeline's configuration. Once the version's been updated in Git what will change the pipeline and update Concourse to use it?

We can parameterize the build no and concourse set pipeline job will reset the pipeline dynamically when there is chnage to github.
we are doing this by storing artifacts in S3 and downloading from S3, but we wanted to have Jfrog resource should have that feature so that we can deploy whatever the build we want to deploy to any environment
S3 resource option:
regexp: directory_on_s3/release-(.*).tgz

Ex: 
parameter  file 
build_no: 11656400

resources:
- name: artifacts
  type: artifactory-resource
  source:
    uri: https://repo.example.com
    username: admin
    password: secret
    build_name: my-build
    build_no: ((build_no))

**Comment by Ambarisha-006** [comment]
build_no should be optional parameter
if we pass build no it will refer to specific build, else it will work as it is working now

When we pass build_no:
Then concourse artifact build history can reflect with lower build versions 
Or
It can reflect with specified build

**Comment by Ambarisha-006** [comment]
@philwebb @wilkinsona Any update/input on this? 
This requirement helps a lot for large and multi environment deployments

It provides an option to download whatever the build we want to download from jfrog and install in any multi tenant environment, instead of referring to latest build in jfrog. 
Imagine there are 10 customers in 10 different AWS environment independent prod pipelines, each client wants to install mmm, nnnn, ...., xxxxx build.

**Comment by philwebb** [comment]
We don't have any need for this functionality ourselves currently so we've not had much time to look at the request. Looking at the [Concourse documentation](https://concourse-ci.org/resources.html#schema.resource.version) and the ["Fetching a repo pinned to a specific commit" section in the Git resource](https://github.com/concourse/git-resource#example) I wonder if we already support this.

@Ambarisha-006 Have you tried the following?

```yaml
resources:
- name: artifacts
  type: artifactory-resource
  source:
    uri: https://repo.example.com
    username: admin
    password: secret
    build_name: my-build
  version:
    build_no: 11656400
```

**Comment by philwebb** [comment]
I'm going to assume the above works and close this one. I can reopen if that's not the case.
