### ISSUE TITLE
curl: (3) Illegal characters found in URL

### ISSUE THREAD

**Issue by mtvann71** [spring-io/artifactory-resource#97]
I'm getting this error occasionally when uploading or downloading artifacts from artifactory.  It seems to happen when fetching (get or put) the same resource multiple times.  Fetching new versions of the resource works ok.  Any idea what is going on?

**Comment by philwebb** [comment]
Are you sure that's related to this project? We don't execute `curl` so I suspect your issue is either with some shell script somewhere or Artifactory itself.

**Comment by mtvann71** [comment]
Isn't curl used under the covers with jfrog?

**Comment by wilkinsona** [comment]
JFrog's code may use curl, but none of the code in this repository does so.
