### ISSUE TITLE
Include build timestamp in fetch query used to retrieve artifacts

### ISSUE THREAD

**Issue by philwebb** [spring-io/artifactory-resource#98]
The fetch query in https://github.com/spring-io/artifactory-resource/blob/671548d308bab66db9dbc222be25fcd9a64d372b/src/main/java/io/spring/concourse/artifactoryresource/artifactory/HttpArtifactoryBuildRuns.java#L109 currently only uses the build number and name. We recently discovered that it's possible for two builds to have the same name and number so we could improve things by including the build timestamp.

**Comment by philwebb** [comment]
I can't get the AQL to work for this. I tried

```
items.find({"@build.name": "spring-boot", "@build.number": "spring-boot-3.0.x-build-1688", "@build.started": {"$lt": "2023-01-20T10:54:22.963+0000"}})
```

and various other combinations.

The more I think about it, the more I feel like adding the timestamp will make things more brittle. I think we should insist that the build name and number are unique.

**Comment by wilkinsona** [comment]
`@build.timestamp` has the desired effect:

```
items.find({"@build.number":"spring-cloud-bindings-release-7","@build.name":"Spring Cloud Bindings","@build.timestamp":"1656518752515"})
```

That said, I also wonder if it'll make things brittle and agree that we may be better off not doing this.
